config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get '/myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end
  
  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer light-blue darken-1">
    <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Schoolion</h5>
            <p class="grey-text text-lighten-4">Schoolionはビジネスマン向けオンライン学習サイトです。今後さらに提供動画数を充実していきます！乞うご期待！！</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">SNS</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
            </ul>
          </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        © 2016 Copyright REXIT
        <%= link_to "運営者のつぶやき", pages_about_path, :class => "grey-text text-lighten-4 right" %>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
   <ul id="dropdown1" class="dropdown-content mask">
      <li><%= link_to "受講コース", myprojects_path %></li>
      <li><%= link_to "プロフィール", edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content mask">
      <li><%= link_to "受講コース", myprojects_path %></li>
      <li><%= link_to "プロフィール", edit_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
    <nav class="light-blue darken-1 z-depth-2">
      <div class="container">
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo">Schoolion</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><%= link_to "コース", root_path %></li>
              <% if(!user_signed_in?) %>
              <li><%= link_to "会員登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <% else %>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-small" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
              <% end %>
            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><a href="#">コース</a></li>
              <% if(!user_signed_in?) %>
              <li><%= link_to "会員登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <% else %>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
              <%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-small" %>&nbsp;
              <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
              <% end %>
            </ul>
          </div>
      </div>
    </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
		<% type= f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		  toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>