config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get '/myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end
  
  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]

	has_many :tasks

	has_many :subscriptions
	has_many :users, through: :subscriptions

	has_many :reviews

	validates :name, presence: true, length: {maximum: 50}
	validates :content, presence: true, length: {maximum: 500}
	validates :price, presence: true, numericality: {only_integer: true}

	has_attached_file :image, styles: { medium: "680x300>", thumb: "170x75>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


   	def shortname
  		name.length > 25? name[0..25] + "..." : name
  	end

  	def average_rating
  		reviews.blank? ? 0 : reviews.average(:star).round(2)  		
  	end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  
  before_action :authenticate_user!, only: [:list]

  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  	@tasks = @project.tasks.order(:tag)

  	@joined = false

  	if !current_user.nil? && !current_user.projects.nil?
  		@joined = current_user.projects.include?(@project)
  	end

  	@users = @project.users.order('created_at desc').first(10)

  	@review = Review.new
  	@reviews = @project.reviews
  	@hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def list
    if !current_user.nil?
      @projects = current_user.projects
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/index.html.erb
<div class="row" data-no-turbolink>
<br/>

	<% @projects.each do |project| %>
		<%= link_to project do %>
			<div class="col s12 m6 l4">
				<div class="card">
					
					<div class="card-image">
						<%= cl_image_tag("#{project.picture}") %>
					</div>
					
					<div class="card-content" style="height: 6em">
						<span class="card-title grey-text text-darken-4">
							<%= project.shortname %>
						</span>
					</div>

				</div>
			</div>
		<% end %>
	<% end %>

</div>

app/views/project/list.html.erb
<h1>受講コース一覧</h1>

<div class="row" data-no-turbolink>
<br/>

	<% if @projects.count > 0 %>

		<% @projects.each do |project| %>
			<%= link_to project do %>
				<div class="col s12 m6 l4">
					<div class="card">
						
						<div class="card-image">
							<%= cl_image_tag("#{project.picture}") %>
						</div>
						
						<div class="card-content" style="height: 6em">
							<span class="card-title grey-text text-darken-4">
								<%= project.shortname %>
							</span>
						</div>

					</div>
				</div>
			<% end %>
		<% end %>

	<% else %>

		<div class="center">
			<h5>まだ受講コースはありません。</h5>
			<%= link_to "コース一覧に行く", root_path, class: "btn btn-primary" %>
		</div>
	<% end %>

</div>

app/views/project/show.html.erb
<% content_for :head do %>
	<title><%= @project.name %> | Schoolion</title>

	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@schoolion">
	<meta name="twitter:creator" content="@schoolion">
	<meta name="twitter:title" content="<%= @project.name %>">
	<meta name="twitter:description" content="<%= @project.content %>">
	<meta name="twitter:image:src" content="<%= image_url @project.image %>">

	<meta property="og:site_name" content="Schoolion">
	<meta property="og:type" content="website">
	<meta property="og:title" content="<%= @project.name %>">
	<meta property="og:description" content="<%= @project.content %>">
	<meta property="og:image" content="<%= @project.image %>">
<% end %>

<div class="row">
	<div class="col m4">
		<div class="card z-depth-2">
			
			<% if !@joined %>	

				<div class="center">
					<h1><%= @project.price == 0? "無料" : "#{@project.price}円" %></h1>
				</div>
				<div class="card-action center">

					<% if user_signed_in? %>
						<% if @project.price == 0 %>
							<%= form_tag free_path do %>
								<%= hidden_field_tag 'project_id', @project.id %>
								<button type="submit" class="btn pink darken-2">この講義を受講</button>
							<% end %>
						<% else %>

							<%= form_tag pay_path, id:'chargeForm' do %>

								<script src="https://checkout.stripe.com/checkout.js"></script>
								<%= hidden_field_tag 'stripeToken' %>
								<%= hidden_field_tag 'stripeEmail' %>
								<%= hidden_field_tag 'project_id', @project.id %>

								<button id="customButton" type="button" class="btn pink darken-2">この講義を購入</button><br>

								<script>
								var handler = StripeCheckout.configure({
								key: '<%= ENV['STRIPE_PUBLIC_KEY'] %>',
								image: '/img/documentation/checkout/marketplace.png',
								locale: 'auto',
								token: function(token, arg) {
									$('#stripeToken').val(token.id);
									$('#stripeEmail').val(token.email);
									$('#chargeForm').submit();
								}
								});

								$('#customButton').on('click', function(e) {
								// Open Checkout with further options:
								handler.open({
								  name: 'Schoolion',
								  description: '<%= @project.name %>',
								  currency: "jpy",
								  amount: '<%= @project.price %>',
								  email: '<%= current_user.email %>'
								});
								e.preventDefault();
								});
								</script>

							<% end %>
						<% end %>
						
					<% else %>
						<%= link_to new_user_session_path do %>	
							<button type="submit" class="btn pink darken-2">この講義を受講</button>
						<% end %>
					<% end %>

				</div>
			
			<% else %>

				<div class="card-content center">
					<%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-medium" %><br/>
					<h5><%= current_user.name %></h5>
				</div>
				<div class="card-action center">
					<% @users.each do |u| %>
						<span class="valign-wrapper">
							<%= image_tag avatar_url(u), class: "circle responsive-img avatar-small" %>&nbsp;
							<%= u.name %>	
						</span><br/>
					<% end %>
				</div>

			<% end %>

		</div>
	</div>

	<div class="col m8">
		<div class="card z-depth-2">
			<div class="card-image">
				<%= cl_image_tag("#{@project.picture}") %>
			</div>

			<div class="row">
			    <div class="col s12">
			      <ul class="tabs">
			        <li class="tab col s3"><a class="active" href="#about">概要</a></li>
			        <li class="tab col s3"><a href="#videos">講義動画</a></li>
			        <li class="tab col s3"><a href="#discussions">Q＆A</a></li>
			      </ul>
			    </div>
			    <div id="about" class="col s12">
					<div class="card-content grey-text text-darken-4">
						<h5><%= @project.name %></h5>
						<span id="average_rating"></span>
						<p><%= @reviews.count %> <%= @reviews.count > 1? "レビュー" : "レビュー" %></p>
						<hr>
						<%= @project.content %>
					
						<h4>レビュー</h4>
						<div><%= render 'reviews/form' if @joined && !@hasReview %></div>
						<div><%= render 'reviews/index' %></div>
					</div>	    	
			    </div>
			    <div id="videos" class="col s10 offset-s1">
			    	<div class="collection" data-no-turbolink>
						<% @tasks.each do |task| %>
							<% if task.header %>
								<div class="collection-item active">
									<i class="mdi-social-school"> <%= task.title %></i>
								</div>
							<% else %>
								<%= link_to [task.project, task], class: "collection-item" do %>
									<%= task.title %>
								<% end %>
							<% end %>
						<% end %>
					</div>
			    </div>
			    <div id="discussions" class="col s10 offset-s1">
			    	<div id="disqus_thread"></div>
					<script>
					/**
					* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
					* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
					*/
					/*
					var disqus_config = function () {
					this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
					this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
					};
					*/
					(function() { // DON'T EDIT BELOW THIS LINE
					var d = document, s = d.createElement('script');
					var disqus_identifier = '<%= @project.id %>';

					s.src = '//schoolion.disqus.com/embed.js';

					s.setAttribute('data-timestamp', +new Date());
					(d.head || d.body).appendChild(s);
					})();
					</script>
					<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
			    </div>
			 </div>



		</div>
	</div>

</div>

<script>
		$('#average_rating').raty({
			path: '/assets',
			readOnly: true,
			score: <%= @project.average_rating %>
		});
</script>